import Head from "next/head";
import { ReactElement } from "react";

interface LayoutProps {
  children: ReactElement;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <section className="flex min-h-screen w-screen flex-col bg-white">
      <Head>
        <title>Thullo - Trello clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {children}
    </section>
  );
}
